apiVersion: v2
name: llmos-operator
description: A Helm chart for LLMOS Operator

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0-dev

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0-app.dev"

keywords:
  - llmos
  - llmos-operator
home: https://github.com/llmos-ai/llmos
sources:
  - https://github.com/llmos-ai/llmos-operator

dependencies:
  - name: kuberay-operator
    version: "1.1.1"
    repository: "https://ray-project.github.io/kuberay-helm"
    condition: kuberay-operator.enabled
    tags:
      - ml-framework
      - ray.io
  - name: redis
    version: 19.6.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - redis
  - name: rook-ceph
    version: 1.14.8
    repository: https://charts.rook.io/release
    condition: rook-ceph.enabled
    tags:
      - rook
      - ceph
