apiVersion: v1
kind: Secret
metadata:
  # Note: using fixed svc name so that it can be used by other dependencies
  name: {{ .Values.global.postgresql.auth.existingSecret }}
  labels:
    {{- include "llmos-controller.labels" . | nindent 4 }}
data:
  pg-username: {{ .Values.global.postgresql.auth.username | b64enc }}
  pg-database: {{ .Values.global.postgresql.auth.database | b64enc }}
  {{- if .Release.IsInstall }}
  pg-admin-password: {{ randAlphaNum 10 | default .Values.global.postgresql.auth.postgresPassword | b64enc }}
  pg-password: {{ randAlphaNum 10 | default .Values.global.postgresql.auth.password | b64enc }}
  pg-replica-password: {{ randAlphaNum 10 | default .Values.global.postgresql.auth.replicationPassword | b64enc }}
  {{- else }}
  # `index` function is necessary because the property name contains a dash.
  # Otherwise (...).data.x-password would have worked too.
  pg-admin-password: {{ index (lookup "v1" "Secret" .Release.Namespace "llmos-postgresql").data "pg-admin-password" }}
  pg-password: {{ index (lookup "v1" "Secret" .Release.Namespace "llmos-postgresql").data "pg-password" }}
  pg-replica-password: {{ index (lookup "v1" "Secret" .Release.Namespace "llmos-postgresql").data "pg-replica-password" }}
  {{- end }}
