apiVersion: v1
kind: Service
metadata:
  name: {{ include "llmos-controller.fullname" . }}
  labels:
    {{- include "llmos-controller.labels" . | nindent 4 }}
    foo: bar
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
{{- if .Values.controller.service.httpsNodePort }}
      nodePort: {{ .Values.controller.service.httpsNodePort }}
{{- end }}
{{- if .Values.controller.service.profilePort }}
    - port: {{ .Values.controller.service.profilePort }}
      targetPort: profile
      protocol: TCP
      name: profile
{{- end }}
  selector:
    {{- include "llmos-controller.selectorLabels" . | nindent 4 }}
