apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ollama.fullname" . }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistent.storageClassName }}
  volumeName: {{ include "ollama.fullname" . }}
  resources:
    requests:
      storage: {{ .Values.persistent.storageSize }}
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ollama.fullname" . }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistent.storageClassName }}
  capacity:
    storage: {{ .Values.persistent.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistent.hostPath }}