---
# Source: rook-ceph-cluster/templates/cephblockpool.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Name }}-block
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: {{ .OperatorNamespace }}.rbd.csi.ceph.com
parameters:
  pool: {{ .BlockPoolName }} # i.e., ceph block pool name
  clusterID: {{ .Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Namespace }}
  csi.storage.k8s.io/fstype: "ext4"
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Namespace }}
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Namespace }}
  imageFeatures: layering
  imageFormat: "2"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
