---
# Source: rook-ceph-cluster/templates/ceph-cluster-sa.yaml
# Service account for Ceph OSDs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-osd
  namespace: {{ .Namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    llmos.ai/created-by: llmos-operator
---
# Source: rook-ceph-cluster/templates/ceph-cluster-sa.yaml
# Service account for Ceph mgrs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-mgr
  namespace: {{ .Namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    llmos.ai/created-by: llmos-operator
---
# Source: rook-ceph-cluster/templates/ceph-cluster-sa.yaml
# Service account for the job that reports the Ceph version in an image
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-cmd-reporter
  namespace: {{ .Namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    llmos.ai/created-by: llmos-operator
---
# Source: rook-ceph-cluster/templates/ceph-cluster-sa.yaml
# Service account for job that purges OSDs from a Rook-Ceph cluster
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-purge-osd
  namespace: {{ .Namespace }}
  labels:
    llmos.ai/created-by: llmos-operator
---
# Source: rook-ceph-cluster/templates/ceph-cluster-sa.yaml
# Service account for RGW server
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-rgw
  namespace: {{ .Namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    llmos.ai/created-by: llmos-operator
---
# Source: rook-ceph-cluster/templates/ceph-cluster-sa.yaml
# Service account for other components
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-default
  namespace: {{ .Namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    llmos.ai/created-by: llmos-operator
