---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: modelfiles.ml.llmos.ai
spec:
  group: ml.llmos.ai
  names:
    kind: ModelFile
    listKind: ModelFileList
    plural: modelfiles
    singular: modelfile
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.model
      name: Model
      type: string
    - jsonPath: .status.modelID
      name: ID
      type: string
    - jsonPath: .status.byteSize
      name: Size
      type: string
    - jsonPath: .status.modifiedAt
      name: Model_Modified
      type: date
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: ModelFile is the Schema for the ModelFiles API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ModelFileSpec defines the desired state of ModelFile
            properties:
              categories:
                items:
                  type: string
                type: array
              description:
                type: string
              fileSpec:
                type: string
              isPublic:
                default: true
                type: boolean
              promptSuggestions:
                items:
                  type: string
                type: array
              tagName:
                type: string
            required:
            - fileSpec
            type: object
          status:
            description: ModelFileStatus defines the observed state of ModelFile
            properties:
              byteSize:
                type: string
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              details:
                properties:
                  families:
                    items:
                      type: string
                    type: array
                  family:
                    type: string
                  format:
                    type: string
                  parameterSize:
                    type: string
                  parentModel:
                    type: string
                  quantizationLevel:
                    type: string
                type: object
              digest:
                type: string
              expiresAt:
                type: string
              isPublic:
                type: boolean
              model:
                type: string
              modelID:
                type: string
              modifiedAt:
                type: string
              size:
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
