---
# Source: rook-ceph-cluster/templates/cephfilesystem.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Name }}-fs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: {{ .OperatorNamespace }}.cephfs.csi.ceph.com
parameters:
  fsName: {{ .FilesystemName }} # e.g., ceph-filesystem
  pool: {{ .FilesystemPoolName }} # e.g., ceph-filesystem-replicated
  clusterID: {{ .Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Namespace }}
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Namespace }}
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Namespace }}
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
