---
# Source: rook-ceph-cluster/templates/cephblockpool.yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: {{ .BlockPoolName }}
  namespace: {{ .Namespace }} # namespace:cluster
spec:
  failureDomain: host
  replicated:
    size: {{ .BlockPoolReplicas }} # default to 2
    requireSafeReplicaSize: true
  parameters:
    min_size: "{{ .BlockPoolMinReplicas }}" # default to 1
  mirroring:
    enabled: false
    # mirroring mode: pool level or per image
    # for more details see: https://docs.ceph.com/docs/master/rbd/rbd-mirroring/#enable-mirroring
    mode: image
  statusCheck:
    mirror:
      disabled: false
      interval: 60s
