---
# Source: rook-ceph-cluster/templates/cephfilesystem.yaml
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: {{ .FilesystemName }}
  namespace: {{ .Namespace }} # namespace:cluster
spec:
  dataPools:
    - name: replicated
      failureDomain: host
      replicated:
        size: {{ .FilesystemDataPoolReplicas }} # default to 2, scale up to 3 if autoscale is set (i.e., node >=3)
  metadataPool:
    replicated:
      size: {{ .FilesystemMetadataPoolReplicas }} # default to 1, scale to 2 if autoscale is set (i.e., node >=3)
  metadataServer:
    activeCount: 1
    activeStandby: true
    priorityClassName: system-cluster-critical
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 200m
        memory: 256Mi
  preserveFilesystemOnDelete: true